#!/usr/bin/env bash

source ~/.cache/wal/colors.sh

hc() {
    herbstclient "$@"
}

hc attr theme.active.inner_color '#000000'
hc attr theme.urgent.inner_color '#000000'
hc attr theme.normal.inner_color '#000000'

hc attr theme.title_color '#ffffff'
hc attr theme.normal.title_color '#898989'

hc attr theme.background_color $background
hc attr theme.active.color $color2
hc attr theme.normal.color $color8
hc attr theme.urgent.color $color3

hc set frame_border_active_color $color2
hc set frame_border_normal_color $color0
hc set frame_bg_normal_color '#000000'
hc set frame_bg_active_color '#000000'

hc attr theme.floating.outer_color black
# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done


